### ISSUE TITLE
Rollulus

### ISSUE THREAD

**Issue by ersinpw** [rollulus/rollulus.github.io#1]
Heyy Roel, lang niet meer gesproken. Ik heb je telefoonnummer en mail adres niet meer. Hoe kan ik jou het best bereiken?

@rollulus

**Comment by rollulus** [comment]
Leuk van je te horen, @ersinpw! Email: mijn GitHub-handle (en tevens de titel van dit issue) apentaartje `xs4all.nl`! 🙋‍♂️
